### PR TITLE
responsive sizing

### PR DESCRIPTION
**Pull request by EulogySnowfall**
This is a basic update for responsive on  "// embed iframe" video share. I add a "?responsive" option to put the video size responsive. Tested on bootstrap3 theme base.

### CODE REVIEW

**Comment by splitbrain** [comment]
Haven't tried the functionality, yet. But your indentation is wrong. Can you please fix it to 4 spaces?

**Comment by EulogySnowfall** [comment]
Hmm, I can check for that, but I had some problem with the space incrementation.  However, tihs touch more the video size then the video alignment. But if you want to chech my pull and change the code has you wich. For me it the result the important thing.

**Comment by borgendorf** [comment]
If it helps get this approved, I needed it so badly I replaced the two files from this PR manually into my Wiki, purged the CSS cache (via the Advanced plugin), and it worked great! I'm using bootstrap3.

**Comment by ERTurner** [comment]
I just implemented this manually and it works great. I totally understand the issues keeping it from getting merged, but I really hope they can get resolved.

**Comment by splitbrain** [comment]
responsive sizing using the sizes `full` and `half`has been added.

**Pull request closed without merging**
